logging:
  level.: warn

#spring:
#  main:
#    banner_mode: 'off'

bloodborne:
  filters:
    # All available attributes: PHYSICAL, BLUNT, THRUST, BLOOD, ARCANE, FIRE, BOLT, SLOW_POISON, RAPID_POISON, FRENZY, BEASTHOOD
    - size: 100
      attributes: [PHYSICAL, BLUNT, THRUST, BLOOD, ARCANE, FIRE, BOLT, SLOW_POISON, RAPID_POISON, FRENZY, BEASTHOOD]
      print: false
    - size: 10
      attributes: [PHYSICAL, BLUNT, THRUST, BLOOD, ARCANE, FIRE, BOLT]
      print: true

  attireSets:
    - name: Cazador con capa corta
      attires:
        - name: Cazador con capa corta
          type: HEAD
          attributes: [50, 50, 40, 50, 20, 50, 30, 5, 11, 14, 16]
        - name: Cazador con capa corta
          type: CHEST
          attributes: [110, 110, 80, 110, 40, 110, 70, 17, 33, 48, 44]
        - name: Cazador con capa corta
          type: HANDS
          attributes: [50, 50, 50, 50, 40, 60, 50, 9, 17, 27, 25]
        - name: Cazador con capa corta
          type: LEGS
          attributes: [60, 60, 50, 60, 50, 60, 50, 10, 19, 30, 27]

    - name: Cazador de Yharnam
      attires:
        - name: Cazador de Yharnam
          type: HEAD
          attributes: [50, 40, 40, 40, 50, 50, 50, 16, 13, 14, 16]
        - name: Cazador de Yharnam
          type: CHEST
          attributes: [110, 80, 90, 90, 80, 100, 90, 48, 40, 41, 48]
        - name: Cazador de Yharnam
          type: HANDS
          attributes: [40, 50, 60, 40, 50, 60, 50, 25, 22, 22, 25]
        - name: Cazador de Yharnam
          type: LEGS
          attributes: [50, 60, 60, 50, 50, 60, 60, 27, 23, 24, 27]

    - name: Cazador Carbonizado
      attires:
        - name: Chistera
          type: HEAD
          attributes: [30, 70, 40, 20, 20, 30, 40, 14, 13, 10, 8]
        - name: Cazador Carbonizado
          type: CHEST
          attributes: [110, 100, 70, 100, 40, 140, 60, 29, 37, 45, 58]
        - name: Cazador Carbonizado
          type: HANDS
          attributes: [60, 40, 40, 50, 40, 70, 40, 15, 20, 24, 30]
        - name: Cazador Carbonizado
          type: LEGS
          attributes: [60, 60, 50, 60, 40, 80, 40, 17, 21, 27, 33]

    - name: Iglesia negro
      attires:
        - name: Iglesia negro
          type: HEAD
          attributes: [40, 40, 40, 50, 60, 50, 50, 20, 19, 2, 13]
        - name: Iglesia negro
          type: CHEST
          attributes: [90, 90, 110, 110, 110, 100, 110, 60, 58, 9, 40]
        - name: Guantes largos de cirujano
          type: HANDS
          attributes: [40, 40, 50, 70, 50, 50, 50, 32, 31, 4, 22]
        - name: Iglesia negro
          type: LEGS
          attributes: [50, 50, 60, 70, 60, 60, 60, 34, 33, 5, 23]

    - name: Iglesia blanco
      attires:
        - name: Iglesia blanco
          type: HEAD
          attributes: [30, 40, 40, 60, 60, 60, 60, 21, 18, 3, 12]
        - name: Iglesia blanco
          type: CHEST
          attributes: [80, 80, 110, 120, 110, 100, 110, 63, 55, 11, 36]
        - name: Guantes largos de cirujano
          type: HANDS
          attributes: [40, 40, 50, 70, 50, 50, 50, 32, 31, 4, 22]
        - name: Iglesia blanco
          type: LEGS
          attributes: [50, 40, 50, 80, 70, 60, 60, 36, 31, 7, 21]

    - name: Negro de Yahar'gul
      attires:
        - name: Yelmo de hierro con capucha negra
          type: HEAD
          attributes: [60, 40, 10, 20, 20, 30, 20, 13, 12, 12, 8]
        - name: Negro de Yahar'gul
          type: CHEST
          attributes: [110, 90, 90, 80, 60, 40, 60, 45, 37, 41, 37]
        - name: Negro de Yahar'gul
          type: HANDS
          attributes: [50, 60, 60, 50, 40, 40, 40, 24, 20, 22, 20]
        - name: Negro de Yahar'gul
          type: LEGS
          attributes: [60, 60, 60, 60, 40, 40, 40, 26, 21, 24, 21]

    - name: Vigilante sepulcral
      attires:
        - name: Vigilante sepulcral
          type: HEAD
          attributes: [40, 40, 50, 40, 50, 40, 50, 16, 16, 32, 13]
        - name: Vigilante sepulcral
          type: CHEST
          attributes: [80, 80, 90, 80, 100, 80, 110, 50, 49, 49, 40]
        - name: Vigilante sepulcral
          type: HANDS
          attributes: [40, 50, 50, 50, 60, 50, 60, 27, 26, 26, 22]
        - name: Vigilante sepulcral
          type: LEGS
          attributes: [50, 50, 60, 50, 60, 46, 60, 29, 28, 28, 23]

    - name: Cazador ceniciento
      attires:
        - name: Gorra de lobo gris
          type: HEAD
          attributes: [50, 40, 40, 50, 20, 50, 30, 9, 12, 19, 37]
        - name: Cazador ceniciento
          type: CHEST
          attributes: [100, 110, 80, 110, 70, 50, 70, 25, 45, 60, 70]
        - name: Cazador ceniciento
          type: HANDS
          attributes: [40, 60, 50, 40, 50, 40, 50, 13, 24, 28, 32]
        - name: Cazador ceniciento
          type: LEGS
          attributes: [60, 50, 50, 60, 50, 50, 50, 15, 26, 30, 37]

    - name: Cazador de Henryk
      attires:
        - name: Cazador de Henryk
          type: HEAD
          attributes: [50, 50, 40, 40, 20, 30, 60, 7, 14, 15, 20]
        - name: Cazador de Henryk
          type: CHEST
          attributes: [100, 100, 80, 80, 70, 100, 150, 21, 41, 45, 60]
        - name: Cazador de Henryk
          type: HANDS
          attributes: [50, 40, 50, 40, 50, 60, 70, 11, 22, 23, 32]
        - name: Cazador de Henryk
          type: LEGS
          attributes: [50, 60, 60, 50, 50, 60, 80, 12, 24, 25, 34]

    - name: Gascoigne
      attires:
        - name: Gascoigne
          type: HEAD
          attributes: [40, 40, 30, 40, 50, 50, 50, 17, 13, 7, 15]
        - name: Gascoigne
          type: CHEST
          attributes: [90, 110, 100, 80, 110, 110, 100, 52, 40, 23, 45]
        - name: Gascoigne
          type: HANDS
          attributes: [40, 60, 60, 50, 60, 60, 40, 28, 21, 12, 24]
        - name: Gascoigne
          type: LEGS
          attributes: [50, 60, 60, 50, 60, 60, 50, 31, 23, 14, 26]

    - name: Buscador de tumbas
      attires:
        - name: Buscador de tumbas
          type: HEAD
          attributes: [40, 40, 50, 50, 60, 50, 50, 18, 16, 4, 15]
        - name: Buscador de tumbas
          type: CHEST
          attributes: [90, 90, 100, 90, 120, 100, 110, 55, 57, 13, 45]
        - name: Buscador de tumbas
          type: HANDS
          attributes: [40, 40, 60, 50, 60, 60, 60, 29, 27, 6, 24]
        - name: Buscador de tumbas
          type: LEGS
          attributes: [50, 60, 60, 60, 70, 60, 50, 31, 29, 8, 26]

    - name: Ejecutor
      attires:
        - name: Chistera
          type: HEAD
          attributes: [30, 70, 40, 20, 20, 30, 40, 14, 13, 10, 8]
        - name: Ejecutor
          type: CHEST
          attributes: [90, 120, 110, 100, 110, 90, 100, 53, 45, 17, 45]
        - name: Ejecutor
          type: HANDS
          attributes: [40, 60, 40, 50, 60, 50, 50, 26, 24, 9, 24]
        - name: Ejecutor
          type: LEGS
          attributes: [50, 70, 50, 60, 60, 60, 50, 30, 26, 10, 26]
